# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e11e99f0bca59958ef66003f0e46b95dfd0efa38ebfe96225361c31625703c0e082e0b75ade6b0e85dde9e73d752944a98df4e0f530d1a75c4b0e5a096d3dd85

test:
  secret_key_base: 2f856ebb00a76221be8e6824bbbb4f17b26384ac3b6b3b7be63fe040ea636dfb02dc1835b12c9c266d44923d0257c32b66be7b7005400ad127e547fb4b506107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
